### ISSUE TITLE
Warning: Couldn't load default plugin "gifsicle"

### ISSUE THREAD

**Issue by lifeofguenter** [TobiX/jenkins-neo2-theme#9] opened 2018-05-17 13:47 UTC
when running `grunt` I get the following error:

```
 grunt
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "imagemin:dynamic" (imagemin) task
Warning: Couldn't load default plugin "gifsicle" Use --force to continue.
```

goes away after running `npm install gifsicle`

**Comment by TobiX** [comment] 2019-08-18 14:08
This might have been fixed along the way (maybe by switching to yarn?) - Closing, because I cannot reproduce it.

**Closed by TobiX** 2019-08-18 14:08 UTC
Labels: bug
